controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

connexion:
    path: /connexion
    controller: App\Controller\SecurityController::login
